### ISSUE TITLE
Join attempt remains at SF7/SF8 on AS923-4

### ISSUE THREAD

**Issue by t0mmyz7** [MultiTechSystems/Dot-AT-Firmware#3]
Hello

we are testing AS923-4 with xdot 4.1.0RC4 FW and Conduit 5.3.5

We notice that the xdot will only attempt to join request at SF7 for 3 times, and then SF8 1 time. This will repeat.

AT+JR=2

![image](https://user-images.githubusercontent.com/31729091/128712833-2d10153b-3dbe-476f-809b-6a73ce92cdcf.png)

We expect the following as we were instructed by multi-tech support, can you clarify this for us please?

our steps to test this,  disable join rx1 and rx2 in the embedded network server.

thanks!

```

In Dot 4.0.4 and later the following should be seen. Previously SF10 was defined for Join Request. 4.0.0 started at SF10 which incurs the greatest backoff. The firmarew tries to stirke a balance between devices deployed near and far from a gateway.


The RP2-1.0.3 recommends using DR2 - DR5 for joining.
https://lora-alliance.org/resource_hub/rp2-1-0-3-lorawan-regional-parameters/


The Dot should cycle through the range in successive join attempts.

SF7, SF7, SF8, SF7, SF7, SF7, SF9, SF7, SF7, SF7, SF10

        static int cnt = 1;

        if ((cnt++ % 12) == 0) {
            dr = lora::DR_2;
        } else if ((cnt % 8) == 0) {
            dr = lora::DR_3;
        } else if ((cnt % 4) == 0) {
            dr = lora::DR_4;
        } else {
            dr = lora::DR_5;
        }
```

**Comment by reissjason** [comment]
It looks like you device send 4 join requests and then maybe a device reset?
There are 7-8s between the first joins and then a 30s pause where the sequence restarts.
SF7, SF7, SF8, SF7
SF7, SF7, SF8, SF7

12 Join Requests without a reset would be needed to reach DR2

**Comment by t0mmyz7** [comment]
Indeed there was ATZ after 5 attemps of join.
it is functional now that we remove it, we see DR2-DR5

![image](https://user-images.githubusercontent.com/31729091/129477166-acb9da5f-5b77-4627-995c-64ed98227935.png)
